server {
    listen 80;
    server_name 3einstalacoes.com.br www.3einstalacoes.com.br _;

    root /usr/share/nginx/html;
    index index.html;

    # Deflate (Gzip)
    gzip on;
    gzip_types text/html text/css text/javascript application/javascript application/json image/svg+xml application/xml;
    gzip_min_length 1024;
    gzip_comp_level 6;
    gzip_vary on;

    # Cache de arquivos estáticos
    location ~* \.(css|js)$ {
        expires 1M;
        add_header Cache-Control "public";
    }

    location ~* \.(png|jpg|jpeg|svg|webp|ico|woff2|woff|ttf)$ {
        expires 1y;
        add_header Cache-Control "public";
        access_log off;
    }

    # Robots e Sitemap
    location = /robots.txt { log_not_found off; }
    location = /sitemap.xml { log_not_found off; }

    # Roteamento de SPA / fallback para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Negar acesso a arquivos ocultos
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
